<?php
/**
 * Implements hook_theme().
 */
function dynamic_toolkit_theme() {
  return [
    'node_listing' => [
      'variables' => [
        'nodes' => [],
        'empty' => '',
      ],
      'template' => 'node-listing-block',
    ],
  ];
}

/**
 * Implements hook_permission().
 */
function dynamic_toolkit_permission() {
  return [
    'view node listing block' => [
      'title' => t('View the node listing block'),
      'description' => t('Allows users to view the node listing block.'),
      'restrict access' => TRUE,
    ],
  ];
}
