<?php

/**
 * @file
 * Primary module hooks for Dynamic Toolkit module.
 */

use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_permission().
 */
function dynamic_toolkit_permission() {
  return [
    'view node listing block' => [
      'title' => t('View the node listing block'),
      'description' => t('Allows users to view the node listing block.'),
      'restrict access' => TRUE,
    ],
  ];
}
